server:
  port: 9090
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: server-lessor-back
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

  jwt:
    life-time: 3600000  # ms
    secret: ${SECRET}
